<link href="{assets}css/datetimepicker.css" rel="stylesheet">
<link href="{assets}css/dataTables.min.css" rel="stylesheet">
<link href="{assets}bootstrap/css/bootstrap.min.css" rel="stylesheet">
<link href="{assets}fonts/font-awesome.min.css" rel="stylesheet">
<link href="{assets}fonts/ionicons.min.css" rel="stylesheet">
<link href="{assets}css/styles.css" rel="stylesheet">
<link href="{assets}css/Login-Form-Clean.css" rel="stylesheet">
<link href="{assets}js/plugin/BootstrapFormHelpers/css/bootstrap-formhelpers.min.css" rel="stylesheet">
<link href="{assets}js/plugin/jquery-minicolors-master/jquery.minicolors.css" rel="stylesheet">
<link href="{assets}css/jquery-ui.css" rel="stylesheet">
<link href="{assets}css/canvas.css" rel="stylesheet">
